kill dataclass type errors with typevar (GEN-337) (#1193)
This PR kills 9 pyright errors of the form

```
error: "Any | type[Any]" is not a class (reportGeneralTypeIssues)
```

by

- modifying `Pytree.dataclass` to ONLY return a decorator, not `type |
decorator`
- adding a type variable so that the type of the wrapped class is
preserved